sudo: false

language: python

python:
  - 2.7

cache: pip

install:
  - "pip install -r tests/requirements.txt"

script:
  - coverage run tests/tests.py

after_success:
- codecov

# command to install dependencies
#install: "pip install -r requirements.txt"
# command to run tests
#script: pytest
